app:
  kafka:
    bootstrap-servers: localhost:29092
    topics:
      is-ready: factory.is.ready
    groupid: factory.is.ready.group
    offset-reset: latest
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/factory
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        max-wait: 30000
        min-idle: 2
    password: superpassword
server:
  port: 8081