version: '3.1'
services:
      redis:
        image: redis:latest
        command: redis-server --requirepass superpassword
        ports:
          - 6379:6379
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
        ports:
          - 22181:21813
      kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
          - zookeeper
        ports:
          - 29092:29092
          - 39093:39092
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092,MINIKUBE_HOST://192.168.65.2:39093
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,MINIKUBE_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      mysql:
        image: mysql:5.7
        platform: linux/x86_64
        restart: always
        environment:
          MYSQL_DATABASES: 'showroom'
          MYSQL_USER: 'user'
          MYSQL_password: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
        ports:
          - 3306:3306
      showroom:
        image: showroom:V1.0.0
        ports:
          - '8080:8080'
        volumes:
          - /Users/j/Downloads/car-factory-template-2/showroom/src/main/resources/application.yaml:/home/app/application.yaml
