version: '3.1'
services:
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
        ports:
          - 22181:2181
      kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
          - zookeeper
        ports:
          - 29092:29092
          - 39092:39092
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKERRPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENNERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092,MINIKUBE_HOST://192.168.49.1:39092
          KAFKA_LISTNER_SCURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,MINIKUBE_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTORY: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      mysql:
        networks:
          - kafka-network
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASES: 'db'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: '1234'
          MYSQL_ROOT_PASSWORD: '1234'
        ports:
          - 3306:3306
      showroom:
        networks:
          - kafka-network
        image: showroom:v1.0.0
